name: mmdate
description: It is a lib that can convert English Date into Myanmar Date. When conversion dates are calculated, based on the date of JDN date ..
version: 1.0.3
homepage: https://github.com/ko-htut/MMDate
# publish_to: none
# author:
#   - Ko Htut

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
